[pytest]
selenium_url = http://localhost:4444
browser_name = chrome
#browser_version = latest
addopts = -s -v --alluredir=allure_results
markers =
    regress: маркер для регрессионных тестов всего флоу Андрея
    smoke: маркер для критических проверок (например, логин)